### ISSUE TITLE
Was ist die "Vereinsversammlung"?

### ISSUE THREAD

**Issue by rnestler** [coredump-ch/statuten#5]
> Der Mitgliederbeitrag wird jährlich erhoben. Die Höhe des Mitgliederbeitrags wird jährlich von der **Vereinsversammlung** festgelegt.

[Source](https://github.com/coredump-ch/statuten/blob/742d4ecb6a0ee0526b741206fb214955c6e674d9/coredump/statuten.tex#L225)

Ist das bewusst *Vereinsversammlung* oder sollte das Generalversammlung sein?

**Comment by dbrgn** [comment]
Ist das selbe. Wir haben den Begriff von ZGB Art. 64 verwendet. https://www.admin.ch/opc/de/classified-compilation/19070042/index.html#a64

**Comment by dbrgn** [comment]
Ah, habe nicht realisiert dass da ein Gemisch von Begriffen verwendet wurde.

**Comment by rnestler** [comment]
Hmm im verlinkten Gesetzestext wir immer von der Vereinsversammlung gesprochen und nie von der Generalversammlung. Sollten wir alles auf Vereinsversammlung ändern?

**Comment by dbrgn** [comment]
Ist sicher beides OK. Können ja darüber abstimmen :) Ich würde zu Vereinsversammlung tendieren.
